Script started on 2016年03月14日 (週一) 13時47分05秒
]0;F74046496@2015cpp: ~F74046496@2015cpp:~$ whom[Kami;pwd pwd[C[C[C
F74046496
/home/F74046496
]0;F74046496@2015cpp: ~F74046496@2015cpp:~$ giat[K[Kt config -l
user.name=F74046496
user.email=wind1997haha@gmail.com
]0;F74046496@2015cpp: ~F74046496@2015cpp:~$ git col[K[Klone https;[K[Ksl[K;[K://githe[Kub[K[K[K[K[K[Kgity[Khub.com [K/F74046496/lab1.git
Cloning into 'lab1'...
remote: Counting objects: 3, done.[K
remote: Total 3 (delta 0), reused 0 (delta 0), pack-reused 0[K
Unpacking objects:  33% (1/3)   Unpacking objects:  66% (2/3)   Unpacking objects: 100% (3/3)   Unpacking objects: 100% (3/3), done.
]0;F74046496@2015cpp: ~F74046496@2015cpp:~$ exit

Script done on 2016年03月14日 (週一) 13時49分48秒
