Script started on 2016年03月15日 (週二) 02時21分37秒
]0;F74046496@2015cpp: ~/lab1[01;32mF74046496@2015cpp[00m:[01;34m~/lab1[00m$ whoami[K[K[K[K[K[Kvim lab1.cppls[Krm lab1.cppls[Kvim lab1.cppgit push -u origin mastercommit -m 'Question A'ls[Kgit commit -m 'Question A'[1Ppush -u origin master[13Pvim lab1.cppls[Krm lab1.cppls[Kvim lab1.cpp[Kvim lab1.cppls[Krm lab1.cppls[Kvim lab1.cpp[K[K[K[K[K[K[K[K[K[K[K[K./lab1
22
22 11 34 17 52 26 13 40 20 10 5 16 8 4 2 1 
]0;F74046496@2015cpp: ~/lab1[01;32mF74046496@2015cpp[00m:[01;34m~/lab1[00m$ exit

Script done on 2016年03月15日 (週二) 02時22分14秒
